version: "3.7"
services:
  flask:
    build:
      context: webapp
    ports:
      - "5000:5000"
    expose:
      - 5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=/opt/webapp/app.py
